### ISSUE TITLE
add animation to counter

### ISSUE THREAD

**Issue by ddanielsantos** [ddanielsantos/blog#295]
counter starts with 0, then goes to the number stored in Redis (if it exists)

- https://css-tricks.com/animating-number-counters/

**Comment by ddanielsantos** [comment]
```css
@property --num {
  syntax: "<integer>";
  initial-value: 0;
  inherits: false;
}

div {
  transition: --num 2.5s ease-in;
  counter-set: num var(--num);
  font: 800 40px system-ui;
}
div::after {
  content: counter(num);
}
div:hover {
  --num: 100;
}

body {
  margin: 2rem;
}

```
